/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

/**
 *
 * @author GL62
 */
public class hasilbiodata extends javax.swing.JFrame {

    /**
     * Creates new form hasilbiodata
     */
    public hasilbiodata(String nama, String absen, String alamat, String jurusan) {
        initComponents();
        Nama.setText(nama);
         Absen.setText(absen);
          Alamat.setText(alamat);
           Jurusan.setText(jurusan);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("HASIL BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 200, 50);

        Jurusan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jurusan.setText("Jurusan");
        getContentPane().add(Jurusan);
        Jurusan.setBounds(50, 210, 390, 30);

        Nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nama.setText("NAMA");
        getContentPane().add(Nama);
        Nama.setBounds(50, 100, 390, 30);

        Absen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Absen.setText("Absen");
        getContentPane().add(Absen);
        Absen.setBounds(50, 140, 60, 30);

        Kelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kelas.setText("Kelas");
        getContentPane().add(Kelas);
        Kelas.setBounds(50, 180, 360, 30);

        Alamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Alamat.setText("Alamat");
        getContentPane().add(Alamat);
        Alamat.setBounds(50, 240, 390, 30);

        setBounds(0, 0, 470, 450);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hasilbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hasilbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hasilbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hasilbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hasilbiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
