/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

/**
 *
 * @author GL62
 */
public class latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form latihan1
     */
    public latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ang2 = new javax.swing.JTextField();
        ang1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnjumlah = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnkali = new javax.swing.JButton();
        auah = new javax.swing.JTextField();
        btnhasil = new javax.swing.JButton();
        bagi = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jframe/Bundle"); // NOI18N
        jMenuItem1.setText(bundle.getString("latihan1.jMenuItem1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText(bundle.getString("latihan1.jLabel1.text")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 50));

        ang2.setText(bundle.getString("latihan1.ang2.text")); // NOI18N
        ang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang2ActionPerformed(evt);
            }
        });
        jPanel3.add(ang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, 30));

        ang1.setText(bundle.getString("latihan1.ang1.text")); // NOI18N
        ang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ang1ActionPerformed(evt);
            }
        });
        jPanel3.add(ang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, 30));

        jLabel2.setFont(new java.awt.Font("BRUSHSTRIKE", 0, 36)); // NOI18N
        jLabel2.setText(bundle.getString("latihan1.jLabel2.text")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 250, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText(bundle.getString("latihan1.jLabel3.text")); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText(bundle.getString("latihan1.jLabel4.text")); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 40));

        btnjumlah.setText(bundle.getString("latihan1.btnjumlah.text")); // NOI18N
        btnjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjumlahActionPerformed(evt);
            }
        });
        jPanel3.add(btnjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        btnkurang.setText(bundle.getString("latihan1.btnkurang.text")); // NOI18N
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });
        jPanel3.add(btnkurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        btnkali.setText(bundle.getString("latihan1.btnkali.text")); // NOI18N
        btnkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaliActionPerformed(evt);
            }
        });
        jPanel3.add(btnkali, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        auah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auahActionPerformed(evt);
            }
        });
        jPanel3.add(auah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 200, 50));

        btnhasil.setText(bundle.getString("latihan1.btnhasil.text")); // NOI18N
        btnhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhasilActionPerformed(evt);
            }
        });
        jPanel3.add(btnhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        bagi.setText(bundle.getString("latihan1.bagi.text")); // NOI18N
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel3.add(bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 40, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 470));

        setSize(new java.awt.Dimension(702, 514));
    }// </editor-fold>//GEN-END:initComponents

    private void btnjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjumlahActionPerformed
        int  bil1= Integer.parseInt(ang1.getText());
       int bil2=Integer.parseInt(ang2.getText());
   int sadna=bil1+bil2;
   auah.setText(String.valueOf(sadna));// TODO add your handling code here:
    }//GEN-LAST:event_btnjumlahActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        int bil1=Integer.parseInt(ang1.getText());
  int bil2=Integer.parseInt(ang2.getText());
    int sadna=bil1-bil2;
    auah.setText(String.valueOf(sadna));// TODO add your handling code here:
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaliActionPerformed
        int bil1=Integer.parseInt(ang1.getText());
  int bil2=Integer.parseInt(ang2.getText());
    int sadna=bil1*bil2;
    auah.setText(String.valueOf(sadna));// TODO add your handling code here:
    }//GEN-LAST:event_btnkaliActionPerformed

    private void auahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auahActionPerformed

    private void ang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ang2ActionPerformed

    private void btnhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhasilActionPerformed
     int bil1=Integer.parseInt(ang1.getText());
  int bil2=Integer.parseInt(ang2.getText());
    int sadna=bil1%bil2;
    auah.setText(String.valueOf(sadna));   // TODO add your handling code here:
    }//GEN-LAST:event_btnhasilActionPerformed

    private void ang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ang1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ang1ActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
       int bil1=Integer.parseInt(ang1.getText());
  int bil2=Integer.parseInt(ang2.getText());
    int sadna=bil1/bil2;
    auah.setText(String.valueOf(sadna)); // TODO add your handling code here:
    }//GEN-LAST:event_bagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ang1;
    private javax.swing.JTextField ang2;
    private javax.swing.JTextField auah;
    private javax.swing.JButton bagi;
    private javax.swing.JButton btnhasil;
    private javax.swing.JButton btnjumlah;
    private javax.swing.JButton btnkali;
    private javax.swing.JButton btnkurang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
