/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

/**
 *
 * @author GL62
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        piljurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        teks1 = new javax.swing.JTextField();
        teks2 = new javax.swing.JTextField();
        rpl = new javax.swing.JRadioButton();
        tkj = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        video = new javax.swing.JCheckBox();
        program = new javax.swing.JCheckBox();
        anim = new javax.swing.JCheckBox();
        desain = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        keluar = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 40, 120, 40);

        jLabel2.setText("Jurusan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 180, 50, 16);

        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 41, 16);

        jLabel4.setText("Absen");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 130, 41, 16);

        teks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teks1ActionPerformed(evt);
            }
        });
        getContentPane().add(teks1);
        teks1.setBounds(120, 90, 230, 30);
        getContentPane().add(teks2);
        teks2.setBounds(120, 130, 230, 30);

        piljurusan.add(rpl);
        rpl.setText("RPL");
        rpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rplActionPerformed(evt);
            }
        });
        getContentPane().add(rpl);
        rpl.setBounds(250, 180, 50, 25);

        piljurusan.add(tkj);
        tkj.setText("TKJ");
        tkj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkjActionPerformed(evt);
            }
        });
        getContentPane().add(tkj);
        tkj.setBounds(160, 180, 50, 25);

        jLabel5.setText("HOBI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 230, 41, 16);

        video.setText("Video Editing");
        video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoActionPerformed(evt);
            }
        });
        getContentPane().add(video);
        video.setBounds(240, 270, 110, 25);

        program.setText("Programming");
        program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programActionPerformed(evt);
            }
        });
        getContentPane().add(program);
        program.setBounds(120, 240, 110, 25);

        anim.setText("Animator");
        anim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animActionPerformed(evt);
            }
        });
        getContentPane().add(anim);
        anim.setBounds(240, 240, 110, 25);

        desain.setText("Designer");
        desain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desainActionPerformed(evt);
            }
        });
        getContentPane().add(desain);
        desain.setBounds(120, 270, 110, 25);

        jLabel6.setText("HASIL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 340, 34, 16);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 360, 350, 170);

        keluar.setText("Exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(300, 310, 79, 25);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(120, 310, 79, 25);

        hapus.setText("Remove");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(210, 310, 79, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\anjay.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-180, -10, 730, 600);

        setBounds(0, 0, 537, 589);
    }// </editor-fold>//GEN-END:initComponents

    private void rplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rplActionPerformed

    private void tkjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkjActionPerformed

    private void videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoActionPerformed

    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programActionPerformed

    private void animActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animActionPerformed

    private void desainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desainActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
String nama = teks1.getText();
String absen = teks2.getText();
String jurusan;
String hobi="";
//UNTUK PILIHAN JURUSAN
if(rpl.isSelected())
     jurusan="RPL";
else if(tkj.isSelected())
  jurusan="TKJ";
  else 
  jurusan="Belum Diisi";
  //Untuk Pilihan Check BOX
  if(anim.isSelected())
      hobi+=anim.getText()+", ";
  
  if(desain.isSelected())
      hobi+=desain.getText()+", ";
  
  if(program.isSelected())
      hobi+=program.getText()+", ";
 
  if(video.isSelected())
      hobi+=anim.getText()+", "; 
  //Untuk Hasil
  hasil.setText("Nama Anda :" +nama+ "\n Absen Anda: " +absen+"\n Jurusan : "+jurusan+"\nHobi Anda "+hobi );




// TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
teks1.setText(""); 
teks2.setText("");
piljurusan.clearSelection();
hasil.setText("Kan Sangar Ya? Ya KAn?");
program.setSelected(false);
anim.setSelected(false);
desain.setSelected(false);
video.setSelected(false);
tkj.setSelected(false);
rpl.setSelected(false);
// TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void teks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teks1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox anim;
    private javax.swing.JCheckBox desain;
    private javax.swing.JButton hapus;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.ButtonGroup piljurusan;
    private javax.swing.JCheckBox program;
    private javax.swing.JRadioButton rpl;
    private javax.swing.JButton submit;
    private javax.swing.JTextField teks1;
    private javax.swing.JTextField teks2;
    private javax.swing.JRadioButton tkj;
    private javax.swing.JCheckBox video;
    // End of variables declaration//GEN-END:variables
}
